<footer style="clear:both">
            <!--Jira Link-->
            <p><a href="https://sothearithkuy37.atlassian.net/jira/software/projects/A1/summary"
            title="This takes you to Jira">Jira Link</a></p>
            <!--Github Link-->
            <a href="https://github.com/Nam-Tran6/Applied-Group5-Project">Github Link</a>
            <!-- Email Link-->
            <a href="mailto:info@companyname.com">Email</a>
</footer>