<footer style="clear:both">
            <!--Jira Link-->
            <p><a href="https://sothearithkuy37.atlassian.net/jira/software/projects/A1/summary"
            target="_blank" title="This takes you to Jira">Jira Link</a></p>
            <!--Github Link-->
            <a href="https://github.com/Nam-Tran6/Applied-Group5-Project" target="_blank">Github Link</a>
            <!-- Email Link-->
            <a href="mailto:info@thebox.com" target="_blank">Email</a>
</footer>