<header> <!-- Standardized Heading-->

        <!--Logo Image-->
        <img id = "logo" src="images/Storage.png" alt="Diagram of four stacked gray layers">

        <!--Main Heading Information-->
        <div id="title"> 
            <h1>THE BOX</h1>
            <p>Infinitively Squared</p> 
        </div>

        <!--Seperate Slogan on Side-->
        <section id= "slogan">
            <h2>A NEW FRONTIER FOR DATA</h2>
        </section>
    </header>

    <nav> <!--Navigation Bar-->
        <ul> <!--Unordered List-->
            <li><a href="index.php">HOME</a></li> <!--Home Link-->
            <li><a href="job.php">JOBS</a></li> <!--Jobs Link-->
            <li><a href="apply.php">APPLY</a></li> <!--Apply Link-->
            <li><a href="about.php">ABOUT</a></li> <!--About Link-->
            <li><a href="Login.php">Login</a></li> <!-Login Link-->
        </ul>
    </nav>